language: node_js
node_js:
  - "node"

install:
  - echo "nothing to install"

script:
  - echo "nothing to do"

deploy:
  provider: s3
  skip_cleanup: true
  bucket: jeremyjones.tech
  region: us-east-1
  local_dir: app
